name: CMake build CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  cmake:
    name: Build with CMake
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencesi with awalsh128/cache-apt-pkgs-action
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libboost-all-dev
          version: 1.0

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
